### ISSUE TITLE
twitter-friends.pl fails

### ISSUE THREAD

**Issue by davehodg** [miyagawa/web-scraper#14]
daveh$ perl twitter-friends.pl 
Invalid attribute-value selector '[rel=~"contact"]' at /Users/daveh/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Web/Scraper.pm line 129.

**Comment by ghost** [comment]
I am also facing same. Any solution?

**Comment by miyagawa** [comment]
i fixed the selector, but twitter profile page does not show followers info anymore so this script won't work anyway. i'd keep there for a reference.
