### ISSUE TITLE
500 Can't Verify SSL peers without knowing which Certificate Authorities to trust

### ISSUE THREAD

**Issue by peterh32** [miyagawa/web-scraper#25]
Here's the full error;
```
GET https://sfbay.craigslist.org/search/sks failed: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
```
...which I get on craigslist, google, and others including the sample code in the readme

**Comment by peterh32** [comment]
Solved.

need to install Mozilla::CA

Did not need to 'use' it, just install it.

**Comment by marczoutendijk** [comment]
I experienced the same error in january 2023 (in perl code that never had this problem before), and installing Mozilla::CA solved it indeed!
(Computers are so smart they can beat the world champion chess-play, yet they are so dumb they need a human being to solve a stupid certificate error...)
